[project]
name = "zeos-sarcastic-cat-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord>=2.3.2",
    "google-generativeai>=0.8.5",
    "langchain>=0.3.25",
    "langchain-community>=0.3.24",
    "langchain-experimental>=0.3.4",
    "langchain-google-genai>=2.0.10",
    "langchain-groq>=0.3.2",
    "langgraph>=0.4.7",
    "python-dotenv>=1.1.0",
    "yt-dlp>=2025.5.22",
]
